---

- name: Configuraci√≥n de repositorio config
  block:

  - name: Creamos el directorio de instalacion para los repos
    file:
      state: directory
      path: "{{item}}"
    with_items:
      - "{{vscode_config_path}}"

  - name: Settings VS Code
    git:
      repo: git@github.com:ndelucca/vscode-settings.git
      dest: "{{vscode_config_path}}"

  when: repos|bool

