---
ansible_host: localhost
ansible_connection: local
ansible_become_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31383539663464376166356434363934616632353936356433323337363639623932303563363962
  3330393266393039386665613532646262333536326633370a353261306665313332623665373033
  30663233306566663563353265616365313364663036393136316639633934656464366662303765
  3534373563643765370a643561383664666333386561376435366635656538316361343066376362
  3935

common_user_name: ndelucca
common_user_group: ndelucca
common_user_home: /home/ndelucca
common_user_email: nazadelucca@gmail.com
common_user_passwd: "{{ ansible_become_pass }}"

i3_main_screen: HDMI-0
i3_secondary_screen: HDMI-0

