---
i3_config_dir: "{{ common_user_config_dir }}/i3"
i3_config_subdir: "{{ i3_config_dir }}/config.d"
i3_config_font: "{{ common_main_font }}"
i3_config_mod: Mod4

i3_status_dir: "{{ common_user_config_dir }}/i3status"

# Rofi configuration
i3_rofi_config_file: "{{ common_user_config_dir }}/rofi/config.rasi"
i3_rofi_scripts_dir: "{{ common_user_config_dir }}/rofi/scripts"
i3_rofi_launcher: launcher_t1
i3_rofi_launcher_style: style-7
i3_rofi_launcher_file: "{{ i3_rofi_scripts_dir }}/{{ i3_rofi_launcher }}"
i3_rofi_selected_launcher_file: "{{ i3_rofi_scripts_dir }}/i3_launcher"
i3_rofi_powermenu: powermenu_t3
i3_rofi_powermenu_style: style-3
i3_rofi_powermenu_file: "{{ i3_rofi_scripts_dir }}/{{ i3_rofi_powermenu }}"
i3_rofi_selected_powermenu_file: "{{ i3_rofi_scripts_dir }}/i3_powermenu"

# i3 Installation
i3_version: 4.23-1+b1
i3_wm_deb_url: "http://ftp.debian.org/debian/pool/main/i/i3-wm/i3-wm_{{ i3_version }}_amd64.deb"
i3_deb_url: "http://ftp.debian.org/debian/pool/main/i/i3-wm/i3_{{ i3_version }}_amd64.deb"
# GTK Configuration
i3_gtk2_config_dir: "{{ common_user_config_dir }}/gtk-2.0/"
i3_gtk3_config_dir: "{{ common_user_config_dir }}/gtk-3.0/"
